server:
  port: 8083

spring:
  application:
    name: processor-app

  cloud:
    stream:
      bindings:
        output:
          # if you don't provide the group you get an exclusive, auto-delete queue
          group: haliho
          destination: demo-processed
          content-type: application/json
          producer:
            required-groups: haliho
        input:
          # if you don't provide the group you get an exclusive, auto-delete queue
          group: haliho
          destination: demo
          content-type: application/xml


