spring:
  integration:
    poller:
      fixed-delay: 2000
  cloud:
    stream:
      bindings:
        output:
          # if you don't provide the group you get an exclusive, auto-delete queue
          group: haliho
          # only the demo exchange is created, no queue and no bindings
          destination: demo
  application:
    name: source-app

server:
  port: 8081


# consumer group: which means you can have multiple instances of consumers compete for messages from the same queue